host: localhost
user: root
passwd: 3811246E # change this with your own password

sqldb_path : ../commands/create_database.sql
sqltables_path: ../commands/create_tables.sql
stabletables_path: ../commands/stable_tables.sql